---
abstract: 'deal with RFC 2047 encoded words (improved)'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MIME-EncWords
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 1.98
  MIME::Base64: 2.13
  MIME::Charset: v1.10.1
  Test::More: 0
version: v1.014.3
